

// action User
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_FAILURE = 'LOGIN_FACEBOOK_FAILURE'

export const POST_FB_DATA_REQUEST = 'POST_FB_DATA_REQUEST'
export const POST_FB_DATA_SUCCESS = 'POST_FB_DATA_SUCCESS'
export const POST_FB_DATA_FAILURE = 'POST_FB_DATA_FAILURE'

export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK'

export const LOGOUT_FACEBOOK = 'LOGOUT_FACEBOOK'

export const DELETE_FB_PERMISSION_REQUEST = 'DELETE_FB_PERMISSION_REQUEST'
export const DELETE_FB_PERMISSION_SUCCESS = 'DELETE_FB_PERMISSION_SUCCESS'
export const DELETE_FB_PERMISSION_FAILURE = 'DELETE_FB_PERMISSION_FAILURE'

export const LOGOUT = 'LOGOUT'

export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'

//action PackageSearch
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'
